#
#  ██████╗░░█████╗░███████╗███████╗██████╗░░██████╗████████╗░█████╗░██████╗░███╗░░░███╗
#  ██╔══██╗██╔══██╗╚════██║██╔════╝██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗████╗░████║
#  ██████╔╝███████║░░███╔═╝█████╗░░██████╔╝╚█████╗░░░░██║░░░██║░░██║██████╔╝██╔████╔██║
#  ██╔══██╗██╔══██║██╔══╝░░██╔══╝░░██╔══██╗░╚═══██╗░░░██║░░░██║░░██║██╔══██╗██║╚██╔╝██║
#  ██║░░██║██║░░██║███████╗███████╗██║░░██║██████╔╝░░░██║░░░╚█████╔╝██║░░██║██║░╚═╝░██║
#  ╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝╚══════╝╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝
#
#
#




########################################################################################
#                                                                                      #
#                                    KRASLOT ITEM                                      #
#                                                                                      #
########################################################################################

# Pas hier het item aan dat een kraslot moet voorstellen.

kraslot-item:
  item: "PAPER"
  item-name: "&6Kraslot"
  lores:
    - "&5Kraslot"
    - "&5Officieel Minetopia Item"



########################################################################################
#                                                                                      #
#                                       SETTINGS                                       #
#                                                                                      #
########################################################################################

# Pas hier wat extra dingen aan zoals hoeveel geld je krijgt.

settings:
  money:
    minimum: 100
    maximum: 500



########################################################################################
#                                                                                      #
#                                       MESSAGES                                       #
#                                                                                      #
########################################################################################

messages:
  openen:
    title: "&6Kraslot"
    subtitle: "&cAan het krassen..."
  gekrast:
    title: "&6Kraslot Gekrast!"
    subtitle: "&6Je hebt %money% gewonnen, gefeliciteerd!"